### ISSUE TITLE
Can Add Disable Villager Trading options

### ISSUE THREAD

**Issue by cxsorious** [bagdydad/AntiFarm#3]
villager-settings:
prevent-villagers-trading: true

wanderingtrader-settings:
wanderingtrader-trading: true

------------------------------------------------------------
and
Prevent spawner per world
------------------------------------------------------------

mob-spawner-settings: true
prevent-spawn-world:
 World:
  - 'Survivals'
  - 'Nether'
  - 'Bla Bla Bla.......'
 
prevent-break: true
 World:
  - 'Survivals'
  - 'Nether'
  - 'Bla Bla Bla.......'

**Comment by bagdydad** [comment]
These features will be included in the next update I will release.
