### ISSUE TITLE
Slimefun Compatibility (androids)

### ISSUE THREAD

**Issue by mrcoffee1026** [bagdydad/AntiFarm#4]
This plugin appears to be working a bit too well on my server, even.  We run Slimefun here and with that it is possible to craft a "Butcher Android" which can then slaughter mobs for slow collection of drops.  This plugin eliminates the drops for those kills.  Would it be possible to grant an exception for this type of kill (maybe as an option in the config if this is a potential workaround on a server that does NOT have Slimefun).  I believe Slimefun has an API available if we need it for something like this, please let me know.

Thanks!

**Comment by bagdydad** [comment]
The update I published includes the features you want. You can download it from the project's spigot page.
